In [1]:
import pandas as pd

In [2]:
import numpy as np

df = pd.read_csv("AI_Sales_Forecasting_10000_Rows.csv")

print(df.head())
print("Shape:", df.shape)

    Order_ID Customer_ID  Order_Date       Product     Category   Region  \
0  ORD108550    CUST2350  2023-01-01  Coffee Maker   Appliances     East
1  ORD100743    CUST1743  2023-01-01      Keyboard  Electronics    South
2  ORD102331    CUST1531  2023-01-01      Backpack  Accessories    North
3  ORD100559    CUST1559  2023-01-01        Laptop  Electronics  Central
4  ORD107250    CUST1050  2023-01-01  Coffee Maker   Appliances    South

  Sales_Channel Payment_Method  Quantity  Unit_Price  Discount   Revenue
0        Online    Credit Card         1     5473.27    0.1214   4808.88
1    Mobile App    Credit Card         5     1572.40    0.1001   7075.03
2  Retail Store    Net Banking         4     1806.40    0.1134   6406.23
3        Online    Credit Card         1    48001.53    0.0647  44897.41
4        Online           Cash         5     6135.79    0.0665  28637.64
Shape: (10000, 12)

In [3]:
print("Rows and Columns:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Rows and Columns:
(10000, 12)

Column Names:
['Order_ID', 'Customer_ID', 'Order_Date', 'Product', 'Category', 'Region', 'Sales_Channel', 'Payment_Method', 'Quantity', 'Unit_Price', 'Discount', 'Revenue']

Data Types:
Order_ID              str
Customer_ID           str
Order_Date            str
Product               str
Category              str
Region                str
Sales_Channel         str
Payment_Method        str
Quantity            int64
Unit_Price        float64
Discount          float64
Revenue           float64
dtype: object

In [4]:
print("First 5 rows:")
display(df.head())

print("Last 5 rows:")
display(df.tail())

First 5 rows:

,Order_ID,Customer_ID,Order_Date,Product,Category,Region,Sales_Channel,Payment_Method,Quantity,Unit_Price,Discount,Revenue
0,ORD108550,CUST2350,2023-01-01,Coffee Maker,Appliances,East,Online,Credit Card,1,5473.27,0.1214,4808.88
1,ORD100743,CUST1743,2023-01-01,Keyboard,Electronics,South,Mobile App,Credit Card,5,1572.40,0.1001,7075.03
2,ORD102331,CUST1531,2023-01-01,Backpack,Accessories,North,Retail Store,Net Banking,4,1806.40,0.1134,6406.23
3,ORD100559,CUST1559,2023-01-01,Laptop,Electronics,Central,Online,Credit Card,1,48001.53,0.0647,44897.41
4,ORD107250,CUST1050,2023-01-01,Coffee Maker,Appliances,South,Online,Cash,5,6135.79,0.0665,28637.64

Last 5 rows:

,Order_ID,Customer_ID,Order_Date,Product,Category,Region,Sales_Channel,Payment_Method,Quantity,Unit_Price,Discount,Revenue
9995,ORD103813,CUST1213,2025-12-31,Coffee Maker,Appliances,South,Online,UPI,4,7184.15,0.0990,25892.09
9996,ORD107991,CUST1791,2025-12-31,Office Chair,Furniture,East,Online,Debit Card,2,8916.77,0.0977,16091.24
9997,ORD106232,CUST1832,2025-12-31,Headphones,Electronics,West,Retail Store,Net Banking,3,3336.97,0.1061,8949.11
9998,ORD100002,CUST1002,2025-12-31,Bookshelf,Furniture,South,Online,Credit Card,1,7322.18,0.0090,7256.17
9999,ORD106255,CUST1855,2025-12-31,Backpack,Accessories,South,Mobile App,Net Banking,5,1687.43,0.1250,7382.13

In [5]:
missing = df.isnull().sum()

print(missing)

Order_ID          0
Customer_ID       0
Order_Date        0
Product           0
Category          0
Region            0
Sales_Channel     0
Payment_Method    0
Quantity          0
Unit_Price        0
Discount          0
Revenue           0
dtype: int64

In [6]:
missing_percent = (df.isnull().sum() / len(df)) * 100

print(missing_percent)

Order_ID          0.0
Customer_ID       0.0
Order_Date        0.0
Product           0.0
Category          0.0
Region            0.0
Sales_Channel     0.0
Payment_Method    0.0
Quantity          0.0
Unit_Price        0.0
Discount          0.0
Revenue           0.0
dtype: float64

In [7]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [8]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

print(df.dtypes)

Order_ID                     str
Customer_ID                  str
Order_Date        datetime64[us]
Product                      str
Category                     str
Region                       str
Sales_Channel                str
Payment_Method               str
Quantity                   int64
Unit_Price               float64
Discount                 float64
Revenue                  float64
dtype: object

In [9]:
df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Month_Name"] = df["Order_Date"].dt.month_name()
df["Quarter"] = df["Order_Date"].dt.quarter

print(df[["Order_Date", "Year", "Month", "Month_Name", "Quarter"]].head())

  Order_Date  Year  Month Month_Name  Quarter
0 2023-01-01  2023      1    January        1
1 2023-01-01  2023      1    January        1
2 2023-01-01  2023      1    January        1
3 2023-01-01  2023      1    January        1
4 2023-01-01  2023      1    January        1

In [10]:
print("Shape:", df.shape)
print("Date range:", df["Order_Date"].min(), "to", df["Order_Date"].max())

Shape: (10000, 16)
Date range: 2023-01-01 00:00:00 to 2025-12-31 00:00:00

In [8]:
# Daily sales aggregation

daily = (
    df.groupby("Order_Date")
    .agg(
        Revenue=("Revenue", "sum"),
        Quantity=("Quantity", "sum"),
        Orders=("Order_ID", "nunique")
    )
    .reset_index()
)

print("Daily observations:", len(daily))
print(daily.head())
print(daily.tail())

Daily observations: 1096
  Order_Date    Revenue  Quantity  Orders
0 2023-01-01  258563.98        36      13
1 2023-01-02  205339.16        10       6
2 2023-01-03  221963.64        22       8
3 2023-01-04  188159.59        25       5
4 2023-01-05  155205.39        15       6
     Order_Date    Revenue  Quantity  Orders
1091 2025-12-27  454467.27        43      10
1092 2025-12-28  395870.52        55      17
1093 2025-12-29  201468.01        28      12
1094 2025-12-30  188889.58        22       9
1095 2025-12-31  184784.47        27       9

In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv("AI_Sales_Forecasting_10000_Rows.csv")

df["Order_Date"] = pd.to_datetime(df["Order_Date"])

print("Shape:", df.shape)
print("Date range:", df["Order_Date"].min(), "to", df["Order_Date"].max())

Shape: (10000, 12)
Date range: 2023-01-01 00:00:00 to 2025-12-31 00:00:00

In [10]:
# Create daily sales data

daily = (
    df.groupby("Order_Date")
    .agg(
        Revenue=("Revenue", "sum"),
        Quantity=("Quantity", "sum"),
        Orders=("Order_ID", "nunique")
    )
    .reset_index()
)

daily["Order_Date"] = pd.to_datetime(daily["Order_Date"])

print("Daily observations:", len(daily))
print(daily.head())

Daily observations: 1096
  Order_Date    Revenue  Quantity  Orders
0 2023-01-01  258563.98        36      13
1 2023-01-02  205339.16        10       6
2 2023-01-03  221963.64        22       8
3 2023-01-04  188159.59        25       5
4 2023-01-05  155205.39        15       6

In [11]:
# Make sure both Order_Date columns have the same datetime type

daily["Order_Date"] = pd.to_datetime(daily["Order_Date"])

calendar = pd.DataFrame({
    "Order_Date": pd.date_range(
        start="2023-01-01",
        end="2025-12-31",
        freq="D"
    )
})

daily = calendar.merge(
    daily,
    on="Order_Date",
    how="left"
)

# Fill days with no sales
daily["Revenue"] = daily["Revenue"].fillna(0)
daily["Quantity"] = daily["Quantity"].fillna(0)
daily["Orders"] = daily["Orders"].fillna(0)

print("Daily observations after calendar:", len(daily))
print(daily.head())
print(daily.tail())

Daily observations after calendar: 1096
  Order_Date    Revenue  Quantity  Orders
0 2023-01-01  258563.98        36      13
1 2023-01-02  205339.16        10       6
2 2023-01-03  221963.64        22       8
3 2023-01-04  188159.59        25       5
4 2023-01-05  155205.39        15       6
     Order_Date    Revenue  Quantity  Orders
1091 2025-12-27  454467.27        43      10
1092 2025-12-28  395870.52        55      17
1093 2025-12-29  201468.01        28      12
1094 2025-12-30  188889.58        22       9
1095 2025-12-31  184784.47        27       9

In [12]:
# Create complete calendar from 2023 to 2025

calendar = pd.DataFrame({
    "Order_Date": pd.date_range(
        start="2023-01-01",
        end="2025-12-31",
        freq="D"
    )
})

daily = calendar.merge(
    daily,
    on="Order_Date",
    how="left"
)

daily["Revenue"] = daily["Revenue"].fillna(0)
daily["Quantity"] = daily["Quantity"].fillna(0)
daily["Orders"] = daily["Orders"].fillna(0)

print("Daily observations after calendar:", len(daily))
print(daily.head())
print(daily.tail())

Daily observations after calendar: 1096
  Order_Date    Revenue  Quantity  Orders
0 2023-01-01  258563.98        36      13
1 2023-01-02  205339.16        10       6
2 2023-01-03  221963.64        22       8
3 2023-01-04  188159.59        25       5
4 2023-01-05  155205.39        15       6
     Order_Date    Revenue  Quantity  Orders
1091 2025-12-27  454467.27        43      10
1092 2025-12-28  395870.52        55      17
1093 2025-12-29  201468.01        28      12
1094 2025-12-30  188889.58        22       9
1095 2025-12-31  184784.47        27       9

In [13]:
# Create forecasting features

daily["Day"] = daily["Order_Date"].dt.day
daily["Month"] = daily["Order_Date"].dt.month
daily["Year"] = daily["Order_Date"].dt.year
daily["DayOfWeek"] = daily["Order_Date"].dt.dayofweek
daily["Quarter"] = daily["Order_Date"].dt.quarter
daily["DayOfYear"] = daily["Order_Date"].dt.dayofyear
daily["WeekOfYear"] = daily["Order_Date"].dt.isocalendar().week.astype(int)

daily["IsWeekend"] = (
    daily["DayOfWeek"] >= 5
).astype(int)

daily["Trend"] = np.arange(len(daily))

# Lag features
daily["Lag_1"] = daily["Revenue"].shift(1)
daily["Lag_2"] = daily["Revenue"].shift(2)
daily["Lag_3"] = daily["Revenue"].shift(3)
daily["Lag_7"] = daily["Revenue"].shift(7)
daily["Lag_14"] = daily["Revenue"].shift(14)
daily["Lag_21"] = daily["Revenue"].shift(21)
daily["Lag_28"] = daily["Revenue"].shift(28)
daily["Lag_30"] = daily["Revenue"].shift(30)

# Rolling features
daily["Rolling_7"] = (
    daily["Revenue"]
    .shift(1)
    .rolling(7)
    .mean()
)

daily["Rolling_14"] = (
    daily["Revenue"]
    .shift(1)
    .rolling(14)
    .mean()
)

daily["Rolling_30"] = (
    daily["Revenue"]
    .shift(1)
    .rolling(30)
    .mean()
)

daily["RollingStd_7"] = (
    daily["Revenue"]
    .shift(1)
    .rolling(7)
    .std()
)

daily["RollingStd_30"] = (
    daily["Revenue"]
    .shift(1)
    .rolling(30)
    .std()
)

print("Features created successfully.")
print("Shape:", daily.shape)
print(daily.head())

Features created successfully.
Shape: (1096, 26)
  Order_Date    Revenue  Quantity  Orders  Day  Month  Year  DayOfWeek  \
0 2023-01-01  258563.98        36      13    1      1  2023          6
1 2023-01-02  205339.16        10       6    2      1  2023          0
2 2023-01-03  221963.64        22       8    3      1  2023          1
3 2023-01-04  188159.59        25       5    4      1  2023          2
4 2023-01-05  155205.39        15       6    5      1  2023          3

   Quarter  DayOfYear  ...  Lag_7  Lag_14  Lag_21  Lag_28  Lag_30  Rolling_7  \
0        1          1  ...    NaN     NaN     NaN     NaN     NaN        NaN
1        1          2  ...    NaN     NaN     NaN     NaN     NaN        NaN
2        1          3  ...    NaN     NaN     NaN     NaN     NaN        NaN
3        1          4  ...    NaN     NaN     NaN     NaN     NaN        NaN
4        1          5  ...    NaN     NaN     NaN     NaN     NaN        NaN

   Rolling_14  Rolling_30  RollingStd_7  RollingStd_30
0         NaN         NaN           NaN            NaN
1         NaN         NaN           NaN            NaN
2         NaN         NaN           NaN            NaN
3         NaN         NaN           NaN            NaN
4         NaN         NaN           NaN            NaN

[5 rows x 26 columns]

In [14]:
# Remove rows with missing lag/rolling values

daily_model = daily.dropna().reset_index(drop=True)

print("Rows available for modeling:", len(daily_model))

Rows available for modeling: 1066

In [15]:
# Define final model features

features = [
    "Day",
    "Month",
    "Year",
    "DayOfWeek",
    "Quarter",
    "DayOfYear",
    "WeekOfYear",
    "IsWeekend",
    "Trend",
    "Lag_1",
    "Lag_2",
    "Lag_3",
    "Lag_7",
    "Lag_14",
    "Lag_21",
    "Lag_28",
    "Lag_30",
    "Rolling_7",
    "Rolling_14",
    "Rolling_30",
    "RollingStd_7",
    "RollingStd_30"
]

X = daily_model[features]
y = daily_model["Revenue"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1066, 22)
y shape: (1066,)

In [16]:
from sklearn.ensemble import RandomForestRegressor

final_model = RandomForestRegressor(
    n_estimators=500,
    max_features="sqrt",
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

final_model.fit(X, y)

print("Final Random Forest model trained successfully.")

Final Random Forest model trained successfully.

In [19]:
# Generate future dates for Jan-Jun 2026

future_dates = pd.date_range(
    start="2026-01-01",
    end="2026-06-30",
    freq="D"
)

# Keep historical revenue
history = daily_model[
    ["Order_Date", "Revenue"]
].copy()

# Create future dataframe
future = pd.DataFrame({
    "Order_Date": future_dates,
    "Revenue": np.nan
})

# Combine historical + future
forecast_data = pd.concat(
    [history, future],
    ignore_index=True
)

print("Future dates:", len(future_dates))
print("Forecast period:",
      future_dates.min(),
      "to",
      future_dates.max())

Future dates: 181
Forecast period: 2026-01-01 00:00:00 to 2026-06-30 00:00:00

In [21]:
# FIXED: Recursive Daily Revenue Forecast

# Recreate forecast_data
forecast_data = pd.concat(
    [
        daily_model[["Order_Date", "Revenue"]].copy(),
        future[["Order_Date", "Revenue"]].copy()
    ],
    ignore_index=True
)

# Make sure date is datetime
forecast_data["Order_Date"] = pd.to_datetime(
    forecast_data["Order_Date"]
)

# Calendar features
forecast_data["Day"] = forecast_data["Order_Date"].dt.day
forecast_data["Month"] = forecast_data["Order_Date"].dt.month
forecast_data["Year"] = forecast_data["Order_Date"].dt.year
forecast_data["DayOfWeek"] = forecast_data["Order_Date"].dt.dayofweek
forecast_data["Quarter"] = forecast_data["Order_Date"].dt.quarter
forecast_data["DayOfYear"] = forecast_data["Order_Date"].dt.dayofyear
forecast_data["WeekOfYear"] = (
    forecast_data["Order_Date"]
    .dt.isocalendar()
    .week
    .astype(int)
)

forecast_data["IsWeekend"] = (
    forecast_data["DayOfWeek"] >= 5
).astype(int)

forecast_data["Trend"] = np.arange(len(forecast_data))


# Forecast only future rows
future_start = len(daily_model)

for i in range(future_start, len(forecast_data)):

    # Lag features
    forecast_data["Lag_1"] = forecast_data["Revenue"].shift(1)
    forecast_data["Lag_2"] = forecast_data["Revenue"].shift(2)
    forecast_data["Lag_3"] = forecast_data["Revenue"].shift(3)
    forecast_data["Lag_7"] = forecast_data["Revenue"].shift(7)
    forecast_data["Lag_14"] = forecast_data["Revenue"].shift(14)
    forecast_data["Lag_21"] = forecast_data["Revenue"].shift(21)
    forecast_data["Lag_28"] = forecast_data["Revenue"].shift(28)
    forecast_data["Lag_30"] = forecast_data["Revenue"].shift(30)

    # Rolling features
    forecast_data["Rolling_7"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(7)
        .mean()
    )

    forecast_data["Rolling_14"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(14)
        .mean()
    )

    forecast_data["Rolling_30"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(30)
        .mean()
    )

    forecast_data["RollingStd_7"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(7)
        .std()
    )

    forecast_data["RollingStd_30"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(30)
        .std()
    )

    # Get features for current date
    row = forecast_data.loc[i, features]

    # Predict revenue
    prediction = final_model.predict(
        pd.DataFrame(
            [row],
            columns=features
        )
    )[0]

    # Prevent negative revenue
    forecast_data.loc[i, "Revenue"] = max(0, prediction)


print("Daily forecasting completed successfully.")
print()
print("Forecast period:")
print(
    forecast_data.loc[future_start, "Order_Date"],
    "to",
    forecast_data.loc[len(forecast_data) - 1, "Order_Date"]
)

Daily forecasting completed successfully.

Forecast period:
2026-01-01 00:00:00 to 2026-06-30 00:00:00

In [ ]:
# Recursive daily forecasting

future_start = len(history)

for i in range(future_start, len(forecast_data)):

    # Lag features
    forecast_data["Lag_1"] = forecast_data["Revenue"].shift(1)
    forecast_data["Lag_2"] = forecast_data["Revenue"].shift(2)
    forecast_data["Lag_3"] = forecast_data["Revenue"].shift(3)
    forecast_data["Lag_7"] = forecast_data["Revenue"].shift(7)
    forecast_data["Lag_14"] = forecast_data["Revenue"].shift(14)
    forecast_data["Lag_21"] = forecast_data["Revenue"].shift(21)
    forecast_data["Lag_28"] = forecast_data["Revenue"].shift(28)
    forecast_data["Lag_30"] = forecast_data["Revenue"].shift(30)

    # Rolling features
    forecast_data["Rolling_7"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(7)
        .mean()
    )

    forecast_data["Rolling_14"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(14)
        .mean()
    )

    forecast_data["Rolling_30"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(30)
        .mean()
    )

    forecast_data["RollingStd_7"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(7)
        .std()
    )

    forecast_data["RollingStd_30"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(30)
        .std()
    )

    # Get current row
    row = forecast_data.loc[i, features]

    # Predict revenue
    prediction = final_model.predict(
        pd.DataFrame(
            [row],
            columns=features
        )
    )[0]

    # Prevent negative revenue
    forecast_data.loc[i, "Revenue"] = max(0, prediction)

print("Daily forecasting completed successfully.")

C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
C:\Users\hp\OneDrive\Desktop\AI_Sales_Forecasting\venv\Lib\site-packages\sklearn\utils\parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

In [20]:
# Prepare future forecasting data

forecast_data = pd.concat(
    [
        daily_model[["Order_Date", "Revenue"]].copy(),
        future[["Order_Date", "Revenue"]].copy()
    ],
    ignore_index=True
)

# Calendar features
forecast_data["Day"] = forecast_data["Order_Date"].dt.day
forecast_data["Month"] = forecast_data["Order_Date"].dt.month
forecast_data["Year"] = forecast_data["Order_Date"].dt.year
forecast_data["DayOfWeek"] = forecast_data["Order_Date"].dt.dayofweek
forecast_data["Quarter"] = forecast_data["Order_Date"].dt.quarter
forecast_data["DayOfYear"] = forecast_data["Order_Date"].dt.dayofyear
forecast_data["WeekOfYear"] = (
    forecast_data["Order_Date"]
    .dt.isocalendar()
    .week
    .astype(int)
)

forecast_data["IsWeekend"] = (
    forecast_data["DayOfWeek"] >= 5
).astype(int)

forecast_data["Trend"] = np.arange(len(forecast_data))

print("Forecast data prepared successfully.")
print("Rows:", len(forecast_data))
print("Columns:", len(forecast_data.columns))

Forecast data prepared successfully.
Rows: 1247
Columns: 11

In [ ]:
# Recursive daily forecasting

future_start = len(daily_model)

for i in range(future_start, len(forecast_data)):

    # Lag features
    forecast_data["Lag_1"] = forecast_data["Revenue"].shift(1)
    forecast_data["Lag_2"] = forecast_data["Revenue"].shift(2)
    forecast_data["Lag_3"] = forecast_data["Revenue"].shift(3)
    forecast_data["Lag_7"] = forecast_data["Revenue"].shift(7)
    forecast_data["Lag_14"] = forecast_data["Revenue"].shift(14)
    forecast_data["Lag_21"] = forecast_data["Revenue"].shift(21)
    forecast_data["Lag_28"] = forecast_data["Revenue"].shift(28)
    forecast_data["Lag_30"] = forecast_data["Revenue"].shift(30)

    # Rolling features
    forecast_data["Rolling_7"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(7)
        .mean()
    )

    forecast_data["Rolling_14"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(14)
        .mean()
    )

    forecast_data["Rolling_30"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(30)
        .mean()
    )

    forecast_data["RollingStd_7"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(7)
        .std()
    )

    forecast_data["RollingStd_30"] = (
        forecast_data["Revenue"]
        .shift(1)
        .rolling(30)
        .std()
    )

    # Current day's features
    row = forecast_data.loc[i, features]

    # Predict
    prediction = final_model.predict(
        pd.DataFrame(
            [row],
            columns=features
        )
    )[0]

    # Avoid negative revenue
    forecast_data.loc[i, "Revenue"] = max(0, prediction)

print("Daily forecasting completed successfully.")